name: text documents by olof
theme: jekyll-theme-minimal
repository: https://github.com/olof/blog
timezone: Europe/Copenhagen

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title
    output: true

exclude:
 - ".gitignore"
